### ISSUE TITLE
COP4TOP

### ISSUE THREAD

**Issue by AlexU75** [Onto-Med/COP#1]

**Comment by ChristophB** [comment]
Decide on license:
* currently GPL3
* OWL file declares CC BY 4

**Comment by ChristophB** [comment]
Looks like there is an issue with purl.archive.org. I can't register new subdomains. Therefore, and because of more configuration options, I would like to switch to purl.obolibrary.org.

- IRIs are already updated in the development branch
- need to submit changes in https://github.com/Onto-Med/purl.obolibrary.org/tree/add-cop-config to the obolibrary team
- an instance of rickview is running at https://top.imise.uni-leipzig.de/ontology/cop/ (half-functional, new COP version must be released)

**Comment by ChristophB** [comment]
I've found that some GFO references are invalid. For instance, https://purl.org/ontology/gfo/Attributive does not exist. Should we update these cases to https://purl.org/ontology/gfo-light/Attributive?
